name: build

on:
  push:
    branches:
      - main
jobs:
  build:

    env:
      PY_COLORS: "1"
      GLOBAL_PROXY: ${{ secrets.GLOBAL_PROXY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: demo 
      run:  python klp.py 
    - uses: actions/checkout@v4

